- name: Learing how variables cab pick from file
  hosts: localhost
  vars_file: 
  - variables.yaml
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hi I am learning {{Course}}, Trainre is {{Trainer}}, Duration {{Duration}}"