- name: checking data tyoes
  hosts: localhost
  vars:
    NAME: SatishKumat #key values
    Skills: # Skill is type: List
    - DevOps
    - Ansible
    - Lunix
    - Shell
    Experince: # Experince is type: Map, it cotains key:value pairs
      DevOps: 1
      AWS: 1
      Docker: 1
    Trainer: true # type boolean
  tasks:
  - name: Printing key value pairs
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: Printing skills
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: Printing Map
    ansible.builtin.debug:
      msg: "Map: {{Experince}}"

  - name: Printing Boolean
    ansible.builtin.debug:
      msg: "Is He Trainer: {{Trainer}}"